miniapp: zora create
mod-protocol/mod pull request #86
Opened 2023-11-16 14:18 UTC by stephancill

The Zora Create mini app allows users to easily and instantly upload an image and turn it into an NFT.

Besides the miniapp itself, it also introduces a change to `@modprotocol/core` which adds base 64 encoded file data to the file picker return value.

2023-11-20 16:59 UTC, davidfurlong requested changes
looks good, a couple small things remain

2023-11-20 16:59 UTC, davidfurlong commented on examples/api/src/app/api/zora-create/route.ts
> +const { NFT_STORAGE_API_KEY } = process.env;
needs to be added to the `.env.sample`

2023-11-20 16:59 UTC, davidfurlong commented on examples/api/src/app/api/zora-create/route.ts
> +  const title = `Zora Create Mod - ${creator.id} - ${timeString}`;
I think we should let people set a title

2023-11-20 16:59 UTC, davidfurlong commented on examples/api/src/app/api/zora-create/route.ts
> +    process.env.ZORA_ADMIN_PRIVATE_KEY as `0x${string}`
add to .env.sample

2023-12-11 16:06 UTC, davidfurlong requested changes

2023-12-11 16:06 UTC, davidfurlong commented on mods/zora-create/package.json
> +  "name": "@miniapps/zora-create",
@mods/

2023-12-11 16:06 UTC, davidfurlong commented
excited to try this!

2023-12-12 10:55 UTC, stephancill commented on examples/api/src/app/api/zora-create/route.ts
> +  const title = prefilledTitle || `Zora Create Mod - ${timeString}`;
What do you mean by "a cast.fun default title"?

How about `Untitled 12/12/2023` using `new Date().localeDateString`?

Onmod is a bit awkward imo

2023-12-12 13:51 UTC, davidfurlong commented on examples/api/src/app/api/zora-create/route.ts
> +  const title = prefilledTitle || `Zora Create Mod - ${timeString}`;
As in "Cast.fun #{timestamp}" or something. Onmod is awk I agree, so is that date format. not sure

2023-12-12 14:25 UTC, stephancill commented on examples/api/src/app/api/zora-create/route.ts
> +  const title = prefilledTitle || `Zora Create Mod - ${timeString}`;
Do you have an alternative date format in mind?

2023-12-12 14:36 UTC, davidfurlong commented on examples/api/src/app/api/zora-create/route.ts
> +  const title = prefilledTitle || `Zora Create Mod - ${timeString}`;
`31st March, 2021`

2023-12-12 14:54 UTC, stephancill commented on examples/api/src/app/api/zora-create/route.ts
> +  const title = prefilledTitle || `Zora Create Mod - ${timeString}`;
added

2024-01-09 10:33 UTC, davidfurlong commented
> The Zora create API requires the ZORA_ADMIN_PRIVATE_KEY account, which will be creating and owning the NFT contracts to be registered with an email address on the zora website. The user's ethereum address is automatically set as the royalties recipient.

This introduces a rug risk right? Integrators that host their own mod api can use their own admin key, then at some point change the royalty recipient or other settings?

2024-01-09 11:06 UTC, davidfurlong approved these changes
lgtm besides the package version

2024-01-09 11:12 UTC, stephancill commented
> This introduces a rug risk right? Integrators that host their own mod api can use their own admin key, then at some point change the royalty recipient or other settings?

It's a trade off that was made to allow for a wallet-less experience. 

Another option is to make use of message signing and leave it up to the client whether they want to abstract it away or not depending on if they have access to the user's keys or not. I think that may actually be a better way of going about it.

2024-01-09 11:13 UTC, davidfurlong commented
happy to do it the current way for now - but we should make a note of this limitation somewhere, perhaps in the readme of the mod or something

2024-01-09 19:16 UTC, stephancill commented
Upgraded to the latest version of the zora sdk, had to create a patch a bug which was using the wrong account to sign the contract creation message. If it looks good to you we should be good to merge

2024-01-10 08:50 UTC, davidfurlong approved these changes

2024-01-11 18:13 UTC, stephancill commented
Tracking patched issue here

https://github.com/ourzora/zora-protocol/issues/398

2024-01-16 15:55 UTC, merged